Repository JuliaPackaging/Yggdrasil, pull requests merged in 2019-10, with the labels that each got.

#120 Add builder for libcap-ng
  L/Libcap_ng/build_tarballs.jl
Labels: GTK

#113 Add builder for gnome-themes-extra
  G/Gnome_themes_extra/build_tarballs.jl
Labels: GTK

#115 [XSLT] Update script to new BinaryBuilder and upgrade to latest version
  X/XSLT/build_tarballs.jl
Labels: GTK

#121 Add builder for attr
  A/Attr/build_tarballs.jl
Labels: GTK

#138 [GLEW] Build for all platforms
  G/GLEW/build_tarballs.jl
Labels: multimedia 🎧

#92 Split X11 builder in separate builders
  X/X11/build_tarballs.jl
  X/Xorg_compositeproto/build_tarballs.jl
  X/Xorg_damageproto/build_tarballs.jl
  X/Xorg_dri2proto/build_tarballs.jl
  X/Xorg_dri3proto/build_tarballs.jl
  X/Xorg_fixesproto/build_tarballs.jl
  X/Xorg_glproto/build_tarballs.jl
  X/Xorg_inputproto/build_tarballs.jl
  X/Xorg_kbproto/build_tarballs.jl
  X/Xorg_libX11/build_tarballs.jl
  X/Xorg_libXScrnSaver/build_tarballs.jl
  X/Xorg_libXau/build_tarballs.jl
  X/Xorg_libXcomposite/build_tarballs.jl
  X/Xorg_libXcursor/build_tarballs.jl
  X/Xorg_libXdamage/build_tarballs.jl
  X/Xorg_libXdmcp_jll/build_tarballs.jl
  X/Xorg_libXext/build_tarballs.jl
  X/Xorg_libXfixes/build_tarballs.jl
  X/Xorg_libXi/build_tarballs.jl
  X/Xorg_libXinerama/build_tarballs.jl
  X/Xorg_libXrandr/build_tarballs.jl
  X/Xorg_libXrender/build_tarballs.jl
  X/Xorg_libXtst/build_tarballs.jl
  X/Xorg_libXxf86vm/build_tarballs.jl
  X/Xorg_libpthread_stubs/build_tarballs.jl
  X/Xorg_libxcb/build_tarballs.jl
  X/Xorg_libxkbfile/build_tarballs.jl
  X/Xorg_libxshmfence/build_tarballs.jl
  X/Xorg_randrproto/build_tarballs.jl
  X/Xorg_recordproto/build_tarballs.jl
  X/Xorg_renderproto/build_tarballs.jl
  X/Xorg_scrnsaverproto/build_tarballs.jl
  X/Xorg_util_macros/build_tarballs.jl
  X/Xorg_xcb_proto/build_tarballs.jl
  X/Xorg_xextproto/build_tarballs.jl
  X/Xorg_xf86vidmodeproto/build_tarballs.jl
  X/Xorg_xineramaproto/build_tarballs.jl
  X/Xorg_xproto/build_tarballs.jl
  X/Xorg_xtrans/build_tarballs.jl
Labels: GTK :computer:

#132 Define shell function to automatically install license files
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/Rootfs/bundled/conf/profile.d/bb_utils.sh
  0_RootFS/Rootfs/bundled/utils/install_license.sh
Labels: BinaryBuilder :gear:

#136 Add builder for SoftPosit
  S/SoftPosit/build_tarballs.jl
  S/SoftPosit/bundled/patches/makefile.patch
Labels: Science :woman_scientist:

#86 Add GLFW
  G/GLFW/build_tarballs.jl
Labels: multimedia 🎧

#141 Add builder of xkbcomp
  X/Xorg_xkbcomp/build_tarballs.jl
Labels: GTK :computer:

#142 Add builder for Dbus
  D/Dbus/build_tarballs.jl
Labels: GTK :computer:

#145 Add builder for xkeyboard-config
  X/Xorg_xkeyboard_config/build_tarballs.jl
Labels: GTK :computer:

#146 Add builder for at-spi2-core
  A/at_spi2_core/build_tarballs.jl
  D/Dbus/build_tarballs.jl
Labels: GTK :computer:

#147 Add builder for xkbcommon
  X/xkbcommon/build_tarballs.jl
  X/xkbcommon/bundled/patches/meson_build.patch
  X/xkbcommon/bundled/patches/meson_options.patch
Labels: GTK :computer:

#149 Add builder for libXft
  X/Xorg_libXft/build_tarballs.jl
Labels: multimedia 🎧

#148 Add builder for at-spi2-atk
  A/at_spi2_atk/build_tarballs.jl
  A/at_spi2_atk/bundled/patches/meson_build.patch
Labels: GTK :computer:

#150 Remove all references to old X11_jll package
  C/Cairo/build_tarballs.jl
  G/GLEW/build_tarballs.jl
  G/GLFW/build_tarballs.jl
  G/gdk_pixbuf/build_tarballs.jl
  L/Libepoxy/build_tarballs.jl
  L/Libglvnd/build_tarballs.jl
  L/Libpciaccess/build_tarballs.jl
  S/SDL2/build_tarballs.jl
Labels: GTK :computer:

#155 added libvorbis builder
  L/libvorbis/build_tarballs.jl
Labels: multimedia 🎧

#156 added x264 builder
  X/x264/build_tarballs.jl
Labels: multimedia 🎧

#88 add ffmpeg builders
  F/FFMPEG/build_tarballs.jl
  O/Ogg/README.md
Labels: multimedia 🎧

#85 Add builder for GTK3
  G/GTK3/build_tarballs.jl
  G/GTK3/bundled/patches/gdkwindow-quartz_c.patch
  G/GTK3/bundled/patches/meson_build.patch
Labels: GTK :computer:

#157 Improve link args in meson cross file for PowerPC64
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/meson.j2
Labels: GTK :computer:

#160 Add builder for FLAC
  F/FLAC/build_tarballs.jl
Labels: multimedia 🎧

#162 Added libsndfile builder
  L/libsndfile/build_tarballs.jl
Labels: multimedia 🎧

#154 added libfdk
  L/libfdk_aac/build_tarballs.jl
Labels: multimedia 🎧

#161 Build gnome_themes_extra for the rest of the platforms
  G/Gnome_themes_extra/build_tarballs.jl
Labels: GTK :computer:

#134 Add Geant4
  G/Geant4/build_tarballs.jl
Labels: Science :woman_scientist:
