Repository JuliaPackaging/Yggdrasil, pull requests merged in 2019-12, with the labels that each got.

#252 Add builder for PROJ
  P/PROJ/build_tarballs.jl
Labels: Science :woman_scientist:

#299 [AZP] Limit BB `nproc` to 10
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#127 Add builder for Python
  P/Python/build_tarballs.jl
  P/Python/bundled/patches/cross_compile_configure_ac.patch
Labels: Python 🐍, Windows 🙄, long shot :bow_and_arrow:

#133 Add LCIO builder
  L/LCIO/build_tarballs.jl
Labels: Science :woman_scientist:

#317 Build a LLVM9 bootstrapping shard
  0_RootFS/LLVMBootstrap@6/bundled/patches/0001-llvm6_compiler_rt_musl.patch
  0_RootFS/LLVMBootstrap@6/bundled/patches/0002-llvm6_libcxx_musl.patch
  0_RootFS/LLVMBootstrap@6/bundled/patches/0003-llvm6_clang_musl_gcc_detector.patch
  0_RootFS/LLVMBootstrap@7/bundled/patches/0001-llvm7_compiler_rt_musl.patch
  0_RootFS/LLVMBootstrap@7/bundled/patches/0002-llvm7_libcxx_musl.patch
  0_RootFS/LLVMBootstrap@7/bundled/patches/0003-llvm7_clang_musl_gcc_detector.patch
  0_RootFS/LLVMBootstrap@8/bundled/patches/0001-llvm8_compiler_rt_musl.patch
  0_RootFS/LLVMBootstrap@8/bundled/patches/0002-llvm8_libcxx_musl.patch
  0_RootFS/LLVMBootstrap@8/bundled/patches/0003-llvm8_clang_musl_gcc_detector.patch
  0_RootFS/LLVMBootstrap@9/build_tarballs.jl
  0_RootFS/LLVMBootstrap@9/bundled/patches/0002-llvm8_libcxx_musl.patch
  0_RootFS/llvm_common.jl
Labels: LLVM :dragon:

#123 Add builder for SDL2_ttf
  S/SDL2_ttf/build_tarballs.jl
  S/SDL2_ttf/bundled/patches/Makefile_in_dont_build_programs.patch
  S/SDL2_ttf/bundled/patches/configure_in-v2.0.15.patch
Labels: Windows 🙄, long shot :bow_and_arrow:, multimedia 🎧

#346 Add flag to `auto_install_license` to check success
  0_RootFS/Rootfs/bundled/conf/profile.d/license_utils.sh
Labels: BinaryBuilder :gear:
