Repository JuliaPackaging/Yggdrasil, pull requests merged in 2019-11, with the labels that each got.

#166 Add builder for mpg123
  M/mpg123/build_tarballs.jl
Labels: multimedia 🎧

#164 Add builder for libmodplug
  L/libmodplug/build_tarballs.jl
Labels: multimedia 🎧

#167 Add builder for libwebp
  L/libwebp/build_tarballs.jl
Labels: multimedia 🎧

#170 Add script for OptimPack
  O/OptimPack/build_tarballs.jl
Labels: Science :woman_scientist:

#187 Move condition of building to the job instead of each step
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#181 More appropriate name for runner job in Azure Pipelines
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#186 Deploy JLL package only if source branch is master
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#188 Improve .env
  .ci/.env
Labels: meta :deciduous_tree:

#185 Tag Docker image using System.JobId instead of Build.SourceVersion
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#183 Trigger build of FFMPEG dependencies
  L/libfdk_aac/build_tarballs.jl
  L/libvorbis/build_tarballs.jl
Labels: multimedia 🎧

#165 Add builder for Opus
  O/Opus/build_tarballs.jl
Labels: multimedia 🎧

#193 Colourful output in Docker
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#194 Update README.md to reflect recent changes to BB and Yggdrasil
  README.md
Labels: meta :deciduous_tree:

#198 [LibVPX] Upgrade to latest stable version and build for PowerPC
  L/LibVPX/build_tarballs.jl
  L/LibVPX/patches/macos.patch
Labels: multimedia 🎧

#196 [WCS] Retrigger build to eradicate symlinks from Windows tarballs
  W/WCS/build_tarballs.jl
Labels: Science :woman_scientist:

#159 Use default GCC version for builders using meson
  A/ATK/build_tarballs.jl
  A/at_spi2_atk/build_tarballs.jl
  A/at_spi2_core/build_tarballs.jl
  G/GTK3/build_tarballs.jl
  G/gdk_pixbuf/build_tarballs.jl
  X/xkbcommon/build_tarballs.jl
Labels: GTK :computer:

#202 add darknet
  D/Darknet/build_tarballs.jl
  D/Darknet/bundled/patches/gemmc_windows_64bit.patch
  D/Darknet/bundled/patches/getopt_windows.patch
  D/Darknet/bundled/patches/windows_headers_case.patch
  D/Darknet/bundled/patches/windows_ldflags.patch
Labels: long shot :bow_and_arrow:

#184 [FFMPEG] Update builder
  F/FFMPEG/build_tarballs.jl
Labels: multimedia 🎧

#200 wrap of spglib
  S/spglib/build_tarballs.jl
Labels: Science :woman_scientist:

#206 add FastTransforms builder
  F/FastTransforms/build_tarballs.jl
Labels: Science :woman_scientist:

#225 [AZP] Map the token
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#221 Further improve README.md
  README.md
Labels: meta :deciduous_tree:

#220 Add Rmath
  R/Rmath/build_tarballs.jl
Labels: Science :woman_scientist:

#218 adds libportaudio builder
  L/libportaudio/build_tarballs.jl
Labels: multimedia 🎧

#223 [ASL] Use Clang for FreeBSD, some other fixes
  A/ASL/build_tarballs.jl
Labels: Science :woman_scientist:

#235 [GEOS] Remove -g options to compilers to reduce size
  G/GEOS/build_tarballs.jl
Labels: Science :woman_scientist:

#241 [Mineos] Add builder for Mineos
  M/Mineos/build_tarballs.jl
Labels: Science :woman_scientist:

#239 [FFMPEG] Fix name of library file for Windows
  F/FFMPEG/build_tarballs.jl
Labels: multimedia 🎧

#216 add GibbsSeaWater
  G/GibbsSeaWater/build_tarballs.jl
Labels: Science :woman_scientist:
