Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-11, with the labels that each got.

#1674 Bump mbedtls to v2.24.0
  M/MbedTLS/build_tarballs.jl
  M/MbedTLS/bundled/patches/fix_incorrect_EOF_check.patch
Labels: julia :purple_heart: :heart: :green_heart:

#2035 [MPFR] Rebuild for Julia 1.6+ as v4.1.1, requiring GMP 6.2.0+
  M/MPFR/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2036 Another batch of v1.6 JLLs
  L/LibSSH2/build_tarballs.jl
  L/LibUV/build_tarballs.jl
  S/SuiteSparse/SuiteSparse/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2044 Push JLL package _before_ uploading binaries
  .ci/register_package.jl
Labels: meta :deciduous_tree:

#1687 Bump JLL wrapper: PCRE2_jll
  P/PCRE2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2037 [LLVM@11] Build for v1.6+ and experimental platforms like aarch64-darwin
  .ci/Manifest.toml
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh
  0_RootFS/common.jl
  0_RootFS/gcc_common.jl
  L/LLVM/LLVM_full@11.0.0/build_tarballs.jl
  L/LLVM/common.jl
  azure-pipelines.yml
Labels: julia :purple_heart: :heart: :green_heart:

#2064 [AZP] Pay attention to BBB hash as well
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#2073 [CUDA] Upgrade to v11.1.1.
  C/CUDA/CUDA_full@11.1/build_tarballs.jl
Labels: cuda :joystick:

#2111 Update HDF5 to v1.12
  H/HDF5/build_tarballs.jl
Labels: HDF5 :five:

#2177 [CUDA] Include cuda-memcheck.
  C/CUDA/CUDA@10.0/build_tarballs.jl
  C/CUDA/CUDA@10.1/build_tarballs.jl
  C/CUDA/CUDA@10.2/build_tarballs.jl
  C/CUDA/CUDA@11.0/build_tarballs.jl
  C/CUDA/CUDA@11.1/build_tarballs.jl
  C/CUDA/CUDA@9.0/build_tarballs.jl
  C/CUDA/CUDA@9.2/build_tarballs.jl
Labels: cuda :joystick:

#2196 Add an additional LLVM patch.
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0060-llvm-invalid-addrspacecast-sink.patch
Labels: LLVM :dragon:
