Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-04, with the labels that each got.

#687 Small fixes to LLVM9
  L/LLVM/LLVM_full@9.0.1/bundled/llvm_patches/9999-llvm-symver-jlprefix.patch
Labels: LLVM :dragon:

#656 Rework CUDA JLLs
  C/CUDA/CUDA_full@10.0/build_tarballs.jl
  C/CUDA/CUDA_full@10.1/build_tarballs.jl
  C/CUDA/CUDA_full@10.2/build_tarballs.jl
  C/CUDA/CUDA_full@9.0/build_tarballs.jl
  C/CUDA/CUDA_full@9.2/build_tarballs.jl
  C/CUDA/build_tarballs.jl
Labels: cuda :joystick:

#751 rebuild python for PPC
  P/Python/build_tarballs.jl
Labels: Python :snake:

#777 [AZP] Bump RegistryTools version
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#780 Integrate with AZP logging
  .ci/Manifest.toml
  .ci/Project.toml
  H/HelloWorldC/build_tarballs.jl
Labels: meta :deciduous_tree:

#828 Don't use abort in _check
  0_RootFS/Rootfs/bundled/utils/sandbox.c
Labels: BinaryBuilder :gear:

#690 Add the SPIRV to LLVM translator.
  S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@10/build_tarballs.jl
  S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@8/build_tarballs.jl
  S/SPIRV_LLVM_Translator/SPIRV_LLVM_Translator@9/build_tarballs.jl
  S/SPIRV_LLVM_Translator/common.jl
Labels: LLVM :dragon:

#838 Add BB service client
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/Rootfs/bundled/utils/bb.c
Labels: BinaryBuilder :gear:

#926 [PlatformSupport] Link `${sysroot}/usr/local` to entire `${prefix}`
  0_RootFS/PlatformSupport/build_tarballs.jl
Labels: BinaryBuilder :gear:

#937 Add flagon script to convert platform-specific flags to compiler
  0_RootFS/Rootfs/bundled/utils/flagon
Labels: BinaryBuilder :gear:

#895 [PlatformSupport] Set Fortran compiler in CMake toolchain files
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_clang.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_gcc.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_clang.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_gcc.j2
Labels: BinaryBuilder :gear:
