Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-10, with the labels that each got.

#1692 [LLVM] prep LLVM 11
  L/LLVM/LLVM_full@11.0.0/build_tarballs.jl
  L/LLVM/LLVM_full@11.0.0/bundled/libcxx_patches/7005_libcxx_musl.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0001-llvm-D27629-AArch64-large_model_6.0.1.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0002-llvm8-D34078-vectorize-fdiv.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0003-llvm-6.0-NVPTX-addrspaces.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0004-llvm-7.0-D44650.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0005-llvm-6.0-DISABLE_ABI_CHECKS.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0016-llvm7-revert-D44485.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0050-llvm-julia-tsan-custom-as.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/9999-llvm-symver-jlprefix.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0006-D50010-VNCoercion-ni.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0041-D80101.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0042-D84031.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0046-D85553.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0050-unique_function_clang-sa.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0100-revert-sdk-requirement-tsan.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0101=fix-darwin-tsan-on-old-sdks.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0700-clang-shlib-mingw.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0702-apple-codesign.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0703-apple-10..12.patch
  L/LLVM/LLVM_full@11.0.0/bundled/patches/0710-cmake-mingw-keyword.patch
  L/LLVM/common.jl
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#1725 [AZP] Update BinaryBuilder
  .ci/Manifest.toml
  H/HelloWorldC/build_tarballs.jl
Labels: meta :deciduous_tree:

#1728 LLVM patch maintenance
  L/LLVM/LLVM_full@10.0.1/bundled/llvm_patches/0032-llvm-D75072-SCEV-add-type.patch
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#1750 Update BinaryBuilderBase to latest (with meta JSON fix)
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#1761 [AZP] Fix detection of `[skip build]` and update wrappers for HWF
  H/HelloWorldFortran/build_tarballs.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#1783 [AZP] [FFMPEG] Bump BinaryBuilder to fix Windows wrappers for FFMPEG
  .ci/Manifest.toml
  F/FFMPEG/FFMPEG/build_tarballs.jl
Labels: meta :deciduous_tree:

#1789 Goodbyte `arctic3`, hello `amdci7`
  .ci/azp_agent/.env
  .ci/azp_agent/install_agents.sh
Labels: meta :deciduous_tree:

#1704 Add libjulia 1.4.2
  L/libjulia/common.jl
  L/libjulia/libjulia@1.4/build_tarballs.jl
  L/libjulia/libjulia@1.4/bundled/patches/0001-flisp-system.patch
  L/libjulia/libjulia@1.4/bundled/patches/0002-libuv-system.patch
  L/libjulia/libjulia@1.4/bundled/patches/0003-flisp.boot.patch
  L/libjulia/libjulia@1.4/bundled/patches/0004-musl.patch
  L/libjulia/libjulia@1.4/bundled/patches/0005-BUILD_EXE-for-flisp.patch
Labels: julia :purple_heart: :heart: :green_heart:

#1910 [AZP] Update BinaryBuilder to latest version
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#1911 [recursively_regenerate_jlls] Add menu to select JLLs to regenerate
  recursively_regenerate_jlls.jl
Labels: meta :deciduous_tree:

#1922 Update .ci/Manifest.toml with latest MacroTools
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#1720 Disable non-POSIX TLS usage in libgomp
  0_RootFS/GCCBootstrap@4/bundled/patches/musl_disable_tls.patch
  0_RootFS/GCCBootstrap@5/bundled/patches/musl_disable_tls.patch
  0_RootFS/GCCBootstrap@6/bundled/patches/musl_disable_tls.patch
  0_RootFS/GCCBootstrap@7/bundled/patches/musl_disable_tls.patch
  0_RootFS/GCCBootstrap@8/bundled/patches/musl_disable_tls.patch
  0_RootFS/GCCBootstrap@9/bundled/patches/musl_disable_tls.patch
  0_RootFS/gcc_common.jl
Labels: BinaryBuilder :gear:

#1946 [AZP] Bump BinaryBuilder* packages to get a bunch of fixes
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#1723 Bump CUDNN to 8.0.4
  C/CUDNN/CUDNN_CUDA101/build_tarballs.jl
  C/CUDNN/CUDNN_CUDA102/build_tarballs.jl
  C/CUDNN/CUDNN_CUDA110/build_tarballs.jl
  C/CUDNN/CUDNN_CUDA111/build_tarballs.jl
  C/CUDNN/common.jl
Labels: cuda :joystick:

#1724 Bump CUTENSOR to 1.2.1
  C/CUTENSOR/CUTENSOR_CUDA111/build_tarballs.jl
  C/CUTENSOR/common.jl
Labels: cuda :joystick:

#1951 Improve libjulia, rebuild libjulia 1.3.1 with the improvements
  L/libjulia/common.jl
  L/libjulia/libjulia@1.3/build_tarballs.jl
Labels: FreeBSD :imp:, julia :purple_heart: :heart: :green_heart:

#1995 [AZP]: Add some `curl` debugging
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#1999 [AZP] Don't download source for a `[skip build]` job
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#2000 [AZP] Always call `download_sources.jl`, but teach it about `SKIP_BUILD`
  .ci/download_sources.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#2013 Regenerate MbedTLS JLL wrapper
  M/MbedTLS/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:
