Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-12, with the labels that each got.

#2207 [AZP] Update BB and BBB to get Rust v1.43 and some fixes to toolchains
  .ci/Manifest.toml
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#2208 [AZP] Update BB to match latest changes in BBB
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2194 [PlatformSupport] Remove toolchains files
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_clang.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_macos_gcc.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_clang.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/cmake_simple_gcc.j2
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/meson.j2
Labels: BinaryBuilder :gear:

#2190 libjulia 1.5: link LibOSXUnwind dynamically
  L/libjulia/common.jl
  L/libjulia/libjulia@1.5/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2200 LibOSXUnwind 0.0.7
  L/LibOSXUnwind/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2238 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2257 add LLVM patches
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0043-llvm-11-D93092-ppc-knownbits.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0045-llvm-11-D93154-globalisel-as.patch
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#2318 [0_RootFS] Fix interpreter of `flagon` utility
  0_RootFS/Rootfs/bundled/utils/flagon
Labels: BinaryBuilder :gear:
