Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-03, with the labels that each got.

#580 Armadillo: use 64-bit integers for 64-bit OpenBLAS
  A/armadillo/build_tarballs.jl
Labels: Science :woman_scientist:

#612 [AZP] Bump BinaryBuilder.jl
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#620 Add EDFlib
  E/EDFlib/build_tarballs.jl
Labels: Science :woman_scientist:

#622 [EDFlib] Add required build options
  E/EDFlib/build_tarballs.jl
Labels: Science :woman_scientist:

#634 Add Luna, software for sleep signal analysis
  L/Luna/build_tarballs.jl
  L/Luna/bundled/patches/fix_it.patch
Labels: Science :woman_scientist:

#659 upgrade to BB 0.2.4
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#658 [LLVM8] backport patches
  L/LLVM/LLVM_full@8.0.1/bundled/llvm_patches/0032-llvm-D75072-SCEV-add-type.patch
  L/LLVM/LLVM_full@8.0.1/bundled/llvm_patches/0040-llvm-8.0-D65174-limit-merge-stores.patch
Labels: LLVM :dragon:

#456 [LLVM] add support for v10
  L/LLVM/LLVM@10.0.0/bundled/llvm_patches/9999-llvm-symver-jlprefix.patch
  L/LLVM/LLVM_full@10.0.0/build_tarballs.jl
  L/LLVM/LLVM_full@10.0.0/bundled/libcxx_patches/7005_libcxx_musl.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0001-llvm-D27629-AArch64-large_model_6.0.1.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0002-llvm8-D34078-vectorize-fdiv.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0003-llvm-6.0-NVPTX-addrspaces.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0004-llvm-7.0-D44650.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0005-llvm-6.0-DISABLE_ABI_CHECKS.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0010-llvm-exegesis-mingw.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0011-llvm-test-plugin-mingw.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0016-llvm7-revert-D44485.patch
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/0020-llvm8-WASM-addrspaces.patch
  L/LLVM/LLVM_full@10.0.0/bundled/patches/0006-D50010-VNCoercion-ni.patch
  L/LLVM/LLVM_full@10.0.0/bundled/patches/0700-clang-shlib-mingw.patch
  L/LLVM/LLVM_full@10.0.0/bundled/patches/0701-darwin-sdk-version.patch
  L/LLVM/LLVM_full@10.0.0/bundled/patches/0702-apple-codesign.patch
  L/LLVM/common.jl
Labels: LLVM :dragon:

#691 [LLVM10] move symver patch to the right location
  L/LLVM/LLVM_full@10.0.0/bundled/llvm_patches/9999-llvm-symver-jlprefix.patch
Labels: LLVM :dragon:
