Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-05, with the labels that each got.

#965 [PlatformSupport] Tell meson we need a wrapper for `i686-linux-musl`
  0_RootFS/PlatformSupport/bundled/buildsystem_toolchains/build_toolchains.sh
Labels: BinaryBuilder :gear:

#984 [AZP] Update BinaryBuilder to latest master
  .ci/Manifest.toml
  .ci/Project.toml
Labels: meta :deciduous_tree:

#986 [AZP] Restore fixes for multiple `build_tarballs`
  .ci/register_package.jl
Labels: meta :deciduous_tree:

#989 [AZP] Upgrade BinaryBuilder to latest master
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#993 [AZP] Fix list of platforms when we have `AnyPlatform`
  .ci/download_sources.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#998 [AZP] Upgrade BB to latest master
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#351 Add builder for Graphviz
  G/Graphviz/build_tarballs.jl
  G/Graphviz/bundled/patches/0001-gvpr-build-native-mkdefs.patch
  G/Graphviz/bundled/patches/0002-do-not-build-dot-config.patch
  G/Graphviz/bundled/patches/0003-sfsetbuf_c_Stat_t_no_st_blksize.patch
  G/Graphviz/bundled/patches/0004-win32_dllexport_dllimport.patch
  G/Graphviz/bundled/patches/0005-missing_libs.patch
  G/Graphviz/bundled/patches/0006-export_neatogen.patch
  G/Graphviz/bundled/patches/0007-remove_missing_def.patch
  G/Graphviz/bundled/patches/0008-export_gvc.patch
  G/Graphviz/bundled/patches/1001-no-ffast-math.patch
Labels: FreeBSD :imp:, Windows 🙄, long shot :bow_and_arrow:

#1034 [WIP] Recipe for Popt
  P/Popt/build_tarballs.jl
  P/Popt/bundled/patches/0001-nl_langinfo.mingw32.patch
  P/Popt/bundled/patches/197416.all.patch
  P/Popt/bundled/patches/217602.all.patch
  P/Popt/bundled/patches/278402-manpage.all.patch
  P/Popt/bundled/patches/318833.all.patch
  P/Popt/bundled/patches/356669.all.patch
  P/Popt/bundled/patches/367153-manpage.all.patch
  P/Popt/bundled/patches/README
  P/Popt/bundled/patches/fix-old-configure-macros.patch
  P/Popt/bundled/patches/get-w32-console-maxcols.mingw32.patch
  P/Popt/bundled/patches/no-uid-stuff-on.mingw32.patch
Labels: Windows 🙄

#1060 Add MIT license file
  LICENSE
Labels: meta :deciduous_tree:

#1062 [AZP] Define `repo` variable in `.ci/register_package.jl` once for all
  .ci/register_package.jl
Labels: meta :deciduous_tree:

#1091 [AZP] Allow skipping building of binaries with keyword in commit message
  .ci/register_package.jl
  H/HelloWorldRust/build_tarballs.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#1098 [AZP] Fix check on the environment variable with the commit message
  H/HelloWorldRust/build_tarballs.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#1102 [AZP] Upgrade BB to latest master
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#1105 [AZP] [Chafa] Update BB to later master and retry building Chafa
  .ci/Manifest.toml
  C/Chafa/build_tarballs.jl
Labels: meta :deciduous_tree:

#1106 [AZP] [Chafa] (re) Update BB to latest master and rebuild Chafa
  .ci/Manifest.toml
  C/Chafa/build_tarballs.jl
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#1107 [AZP] Bumpt BB to latest master
  .ci/Manifest.toml
Labels: meta :deciduous_tree:
