Repository JuliaPackaging/Yggdrasil, pull requests merged in 2020-09, with the labels that each got.

#1623 [RootFS]: Allow setting `--deploy=local` to skip GitHub upload
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/common.jl
  0_RootFS/gcc_common.jl
Labels: BinaryBuilder :gear:

#1630 [AZP] Update BBB to master
  .ci/Manifest.toml
  .ci/Project.toml
  H/HelloWorldCxx/build_tarballs.jl
Labels: meta :deciduous_tree:

#1675 [LLVM10] add patch for clang-sa
  L/LLVM/LLVM_full@10.0.1/bundled/patches/0050-unique_function_clang-sa.patch
  L/LLVM/LLVM_full@10.0.1/bundled/patches/0703-apple-10..12.patch
  L/LLVM/common.jl
Labels: LLVM :dragon:

#1694 Successfully cross-compile libjulia
  L/libjulia/common.jl
  L/libjulia/libjulia@1.5/build_tarballs.jl
  L/libjulia/libjulia@1.5/bundled/patches/0001-flisp-system.patch
  L/libjulia/libjulia@1.5/bundled/patches/0002-libuv-system.patch
  L/libjulia/libjulia@1.5/bundled/patches/0003-flisp.boot.patch
  L/libjulia/libjulia@1.5/bundled/patches/0004-musl.patch
  L/libjulia/libjulia@1.5/bundled/patches/0005-BUILD_EXE-for-flisp.patch
Labels: julia :purple_heart: :heart: :green_heart:

#1705 Add BPF target to LLVM
  L/LLVM/LLVM_full@10.0.1/build_tarballs.jl
  L/LLVM/common.jl
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#1709 [AZP] Update BinaryBuilder to use new JLLWrappers-based JLLs
  .ci/Manifest.toml
  H/HelloWorldCxx/build_tarballs.jl
Labels: meta :deciduous_tree:

#1707 [GCCBootstrap]: Change ARM shard to support armv6l and armv7l
  0_RootFS/common.jl
  0_RootFS/gcc_common.jl
Labels: BinaryBuilder :gear:

#1712 [AZP] Bump BinaryBuilder
  .ci/Manifest.toml
Labels: meta :deciduous_tree:
