Repository JuliaPackaging/Yggdrasil, pull requests merged in 2021-02, with the labels that each got.

#2482 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2473 [LLVMBootstrap] Add version 11.0.1
  0_RootFS/LLVMBootstrap@11/build_tarballs.jl
  0_RootFS/LLVMBootstrap@11/bundled/patches/0002-llvm8_libcxx_musl.patch
  0_RootFS/LLVMBootstrap@11/bundled/patches/0010-add-musl-triples.patch
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/common.jl
  0_RootFS/gcc_common.jl
  0_RootFS/llvm_common.jl
Labels: BinaryBuilder :gear:, LLVM :dragon:

#2506 [Codespaces] Update to Julia v1.6 and BinaryBuilder#master
  .devcontainer/Dockerfile
Labels: meta :deciduous_tree:

#2538 Update Julia version to v1.6.0-rc1
  .ci/azp_agent/.env
  .ci/azp_agent/install_agents.sh
Labels: meta :deciduous_tree:

#2439 [LibCURL] Request macOS 11.0+ on Apple Silicon
  .ci/Manifest.toml
  L/LibCURL/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#2610 [CUDA] Bundle the compute sanitizer.
  C/CUDA/CUDA@11.0/build_tarballs.jl
  C/CUDA/CUDA@11.1/build_tarballs.jl
  C/CUDA/CUDA@11.2/build_tarballs.jl
Labels: cuda :joystick:

#2611 Backport SLJIT fix for Apple Silicon restrictions on mapping WX pages
  P/PCRE2/build_tarballs.jl
  P/PCRE2/bundled/patches/sljit-nomprotect.patch
Labels: julia :purple_heart: :heart: :green_heart:
