Repository JuliaPackaging/Yggdrasil, pull requests merged in 2021-08, with the labels that each got.

#3432 Upgrade CUDA to 11.4.1.
  C/CUDA/CUDA_full@11.4/build_tarballs.jl
Labels: cuda :joystick:

#3433 Upgrade CUDNN to v.8.2.2.
  C/CUDNN/build_10.2.jl
  C/CUDNN/build_11.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#3442 Bump NEO to v21.30.20482.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#3450 Bump libigc to v1.0.8173.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#3452 Bump NEO to v21.31.20514.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#3447 Update FreeBSD support from 11 to 12
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/gcc_common.jl
  RootFS.md
Labels: BinaryBuilder :gear:

#3472 [AZP] Update CI to use newer BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#3473 [Zlib] Touch build_tarballs.jl to trigger rebuild
  Z/Zlib/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3474 [OpenLibm] Touch build_tarballs.jl to trigger a rebuild
  O/OpenLibm/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3476 [LibUV] Touch build_tarballs.jl to trigger a rebuild
  L/LibUV/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3478 [LibUnwind] Touch build_tarballs.jl to trigger a rebuild
  L/LibUnwind/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3479 [GMP] Touch build_tarballs.jl to trigger a rebuild
  G/GMP/GMP@6.2.0/build_tarballs.jl
  G/GMP/GMP@6.2.1/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3480 [MbedTLS] Touch build_tarballs.jl to trigger a rebuild
  M/MbedTLS/MbedTLS@2.24.0/build_tarballs.jl
  M/MbedTLS/MbedTLS@2.24.0/bundled/patches/0003-Prevent-triggering-Clang-12--Wstring-concatenation.patch
  M/MbedTLS/MbedTLS@2.25.0/build_tarballs.jl
  M/MbedTLS/MbedTLS@2.26.0/build_tarballs.jl
  M/MbedTLS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3481 [libblastrampoline] Touch build_tarballs.jl to trigger a rebuild
  L/libblastrampoline/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3483 [MPFR] Touch build_tarballs.jl to trigger a rebuild
  M/MPFR/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3482 [LibSSH2] Touch build_tarballs.jl to trigger a rebuild
  L/LibSSH2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3484 [LibGit2] Touch build_tarballs.jl to trigger a rebuild
  L/LibGit2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3485 [nghttp2] Touch build_tarballs.jl to trigger a rebuild
  N/nghttp2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3487 [OpenBLAS32] Touch build_tarballs.jl to trigger a rebuild
  O/OpenBLAS/OpenBLAS32@0.3.10/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.13/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3488 [OpenBLASHighCoreCount] Touch build_tarballs.jl to trigger a rebuild
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.10/build_tarballs.jl
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.13/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3486 [OpenBLAS] Touch build_tarballs.jl to trigger a rebuild
  O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.13/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3489 [dSFMT] Touch build_tarballs.jl to trigger a rebuild
  D/dSFMT/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3490 [LibCURL] Touch build_tarballs.jl to trigger a rebuild
  L/LibCURL/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3492 [p7zip] Touch build_tarballs.jl to trigger a rebuild
  P/p7zip/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3493 [PCRE2] Touch build_tarballs.jl to trigger a rebuild
  P/PCRE2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3494 [SuiteSparse] Touch build_tarballs.jl to trigger a rebuild
  S/SuiteSparse/SuiteSparse/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3491 [Objconv] Touch build_tarballs.jl to trigger a rebuild
  O/Objconv/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#3498 [AZP] Show how old is the registry in the generator job
  .ci/Project.toml
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#3504 Add LLVM libunwind v12.0.1
  L/LLVMLibUnwind/LLVMLibUnwind@12.0.1/build_tarballs.jl
  L/LLVMLibUnwind/LLVMLibUnwind@12.0.1/bundled/patches/0001-unwind-prologue-epilogue.patch
  L/LLVMLibUnwind/LLVMLibUnwind@12.0.1/bundled/patches/0002-force-dwarf.patch
  L/LLVMLibUnwind/LLVMLibUnwind@12.0.1/bundled/patches/0003-revert-monorepo-requirement.patch
  L/LLVMLibUnwind/LLVMLibUnwind@12.0.1/bundled/patches/0004-freebsd-libgcc-api-compat.patch
  L/LLVMLibUnwind/common.jl
Labels: LLVM :dragon:

#3525 [LLVM_full] Touch build_tarballs.jl to trigger a rebuild
  L/LLVM/LLVM_full@11.0.1/build_tarballs.jl
  L/LLVM/LLVM_full@12.0.1/build_tarballs.jl
  L/LLVM/common.jl
Labels: LLVM :dragon:

#3534 [libLLVM] Bump LLVM_full build revision
  L/LLVM/libLLVM@11.0.1/build_tarballs.jl
  L/LLVM/libLLVM@12.0.1/build_tarballs.jl
Labels: LLVM :dragon:

#3532 [LLVMBootstrap@12] Add a Clang patch for FreeBSD targets
  0_RootFS/LLVMBootstrap@12/bundled/patches/0101-clang-freebsd-triplet.patch
Labels: meta :deciduous_tree:, LLVM :dragon:

#3542 [OpenBLAS] Add v0.3.17
  O/OpenBLAS/OpenBLAS32@0.3.17/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS32@0.3.17/bundled/patches/openblas-winexit.patch
  O/OpenBLAS/OpenBLAS@0.3.17/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS@0.3.17/bundled/patches/openblas-winexit.patch
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/build_tarballs.jl
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/openblas-ofast-power.patch
  O/OpenBLAS/OpenBLASHighCoreCount@0.3.17/bundled/patches/openblas-winexit.patch
  O/OpenBLAS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:
