Repository JuliaPackaging/Yggdrasil, pull requests merged in 2021-12, with the labels that each got.

#3992 [Rust] Update to v1.57.0
  0_RootFS/Rust/build_tarballs.jl
Labels: BinaryBuilder :gear:, rust :crab:

#4012 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#3976 Bump Librsvg to v2.52.4
  L/Librsvg/build_tarballs.jl
  L/Librsvg/bundled/patches/0001-Makefile.am-use-the-correct-EXEEXT-extension-for-the.patch
  L/Librsvg/bundled/patches/librsvg_link_order.patch
Labels: rust :crab:

#1780 [ripgrep] Add builder
  R/ripgrep/build_tarballs.jl
Labels: long shot :bow_and_arrow:, rust :crab:

#4000 [OpenBLAS@0.3.10] Rebuild with 32 threads
  O/OpenBLAS/OpenBLAS@0.3.10/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:, linear algebra

#4016 add WhiteboxTools
  W/WhiteboxTools/build_tarballs.jl
Labels: rust :crab:

#3616 Update tectonic version, enable M1 macs
  T/tectonic/build_tarballs.jl
Labels: rust :crab:

#4035 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
  L/Librsvg/build_tarballs.jl
  T/tectonic/build_tarballs.jl
Labels: meta :deciduous_tree:

#4034 [LLVM] Build 13.0.0+1
  L/LLVM/LLVM_full@13.0.0/build_tarballs.jl
  L/LLVM/LLVM_full_assert@13.0.0/build_tarballs.jl
  L/LLVM/common.jl
  azure-pipelines.yml
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#3969 GCC 4.8.5 for musl: tweak patch to match upstream
  0_RootFS/GCCBootstrap@4/bundled/patches/gcc494_musl.patch
Labels: BinaryBuilder :gear:

#4045 Bump CUDNN to v8.3.1.
  C/CUDNN/build_10.2.jl
  C/CUDNN/build_11.5.jl
  C/CUDNN/build_11.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#4069 [GCCBootstrap] Create symlink `libc.musl-$(arch).so.1` -> `libc.so`
  0_RootFS/gcc_common.jl
Labels: BinaryBuilder :gear:

#4079 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4104 Add a custom zlib to CUDNN on Windows.
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#4133 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/gcc_common.jl
  0_RootFS/llvm_common.jl
Labels: meta :deciduous_tree:

#4138 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:
