Repository JuliaPackaging/Yggdrasil, pull requests merged in 2021-01, with the labels that each got.

#2352 [CUDA] Add v11.2 (entire toolkit).
  C/CUDA/CUDA_full@11.2/build_tarballs.jl
Labels: cuda :joystick:

#2357 [CUDA] Add v11.2.0.
  C/CUDA/CUDA@11.2/build_tarballs.jl
Labels: cuda :joystick:

#2367 [CUDA] Fix permissions of DLLs.
  C/CUDA/CUDA_full@10.0/build_tarballs.jl
  C/CUDA/CUDA_full@10.1/build_tarballs.jl
  C/CUDA/CUDA_full@10.2/build_tarballs.jl
  C/CUDA/CUDA_full@11.0/build_tarballs.jl
  C/CUDA/CUDA_full@11.1/build_tarballs.jl
  C/CUDA/CUDA_full@11.2/build_tarballs.jl
  C/CUDA/CUDA_full@9.0/build_tarballs.jl
  C/CUDA/CUDA_full@9.2/build_tarballs.jl
Labels: cuda :joystick:

#2354 update LLVM PowerPC patches
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0043-llvm-11-D93092-ppc-knownbits.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0046-llvm-11-ppc-half-ctr.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0047-llvm-11-ppc-sp-from-bp.patch
  L/LLVM/LLVM_full@11.0.0/bundled/llvm_patches/0048-llvm-rGb498303066a6-gcc11-header-fix.patch
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#2371 [AZP] Update to latest BinaryBuilder
  .ci/Manifest.toml
  .ci/register_package.jl
Labels: meta :deciduous_tree:

#2372 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2356 [RootFS] Install `samurai` instead of `ninja`
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/Cargo.toml
  0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/Makefile
  0_RootFS/Rootfs/bundled/testsuite/rust/cargo_build/src/main.rs
  0_RootFS/Rootfs/bundled/utils/apk_wrapper.sh
  0_RootFS/Rootfs/bundled/utils/config.guess
  0_RootFS/Rootfs/bundled/utils/config.sub
  0_RootFS/Rootfs/bundled/utils/tar_wrapper.sh
Labels: BinaryBuilder :gear:

#2386 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2408 [AZP] Update BinaryBuilder
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2430 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#2446 LLVM maintenance (PPC + -fno-gnu-unique)
  L/LLVM/LLVM_full@11.0.1/bundled/llvm_patches/0051-llvm-11-D94828-ppc-half-fpconv.patch
  L/LLVM/LLVM_full@11.0.1/bundled/llvm_patches/0053-llvm-11-D94980-CTR-half.patch
  L/LLVM/LLVM_full@11.0.1/bundled/llvm_patches/0054-llvm-11-D94058-sext-atomic-ops.patch
  L/LLVM/LLVM_full_assert@11.0.1/build_tarballs.jl
  L/LLVM/common.jl
Labels: LLVM :dragon:

#2462 [pigz] Create initial build for pigz
  P/pigz/build_tarballs.jl
Labels: FreeBSD :imp:

#2471 [testsuite] Add `float_abi` test with `go`
  0_RootFS/Rootfs/bundled/testsuite/Makefile
  0_RootFS/Rootfs/bundled/testsuite/go/float_abi/Makefile
  0_RootFS/Rootfs/bundled/testsuite/go/float_abi/float_abi.go
Labels: BinaryBuilder :gear:
