Repository JuliaPackaging/Yggdrasil, pull requests merged in 2022-01, with the labels that each got.

#4160 [AZP] Update BinaryBuilderBase and BinaryBuilder
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4179 Add MbedTLS 2.28.0
  M/MbedTLS/MbedTLS@2.28.0/build_tarballs.jl
  M/MbedTLS/MbedTLS@2.28.0/bundled/patches/0001-Remove-flags-not-sopported-by-ranlib.patch
  M/MbedTLS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:

#4204 Build LLVMExtra against LLVM 13 for Julia 1.8.
  L/LLVMExtra/build_tarballs.jl
Labels: LLVM :dragon:

#4218 [HDF5] Update to v1.12.1
  H/HDF5/build_tarballs.jl
Labels: long shot :bow_and_arrow:, HDF5 :five:

#4184 [AZP] add age to registry last updated info
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#4257 [AZP] Round age of registry to second
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#4261 [AZP] Upgrade BinaryBuilder to v0.5.0 and require Julia v1.7
  .ci/Manifest.toml
  .ci/azp_agent/install_agents.sh
  H/HelloWorldC/build_tarballs.jl
Labels: meta :deciduous_tree:

#4267 Bump CUDA compatibility package to 11.6.
  C/CUDA/CUDA_compat/build_tarballs.jl
Labels: cuda :joystick:

#4266 Bump CUDA to 11.6 (part 1).
  C/CUDA/CUDA_full@11.6/build_tarballs.jl
Labels: cuda :joystick:

#4268 Bump CUDA to 11.6 (part 2).
  C/CUDA/CUDA@11.6/build_tarballs.jl
  C/CUDA/CUDA_loader/build_11.6.jl
  C/CUDA/CUDA_loader/build_tarballs.jl
Labels: cuda :joystick:

#4273 Bump CUTENSOR to 1.4.0, include cutensorMg.
  C/CUTENSOR/build_10.2.jl
  C/CUTENSOR/build_11.0.jl
  C/CUTENSOR/build_11.6.jl
  C/CUTENSOR/build_11.jl
  C/CUTENSOR/build_tarballs.jl
Labels: cuda :joystick:

#4275 Bump CUDNN to v8.3.2.
  C/CUDNN/build_10.2.jl
  C/CUDNN/build_11.6.jl
  C/CUDNN/build_11.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#4274 [AZP] Upgrade devcontainer to Julia 1.7
  .devcontainer/Dockerfile
Labels: meta :deciduous_tree:

#4304 [AZP] Do not hard fail if cannot download registry
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#4305 [AZP] Temporarily force use of `us-east` PkgServer
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#4330 [fancy_toys] `get_addable_spec` is now in `BinaryBuilderBase`
  fancy_toys.jl
Labels: meta :deciduous_tree:
