Repository JuliaPackaging/Yggdrasil, pull requests merged in 2022-03, with the labels that each got.

#4518 Bump gmmlib to v22.0.2.
  G/gmmlib/build_tarballs.jl
Labels: oneAPI :one:

#4521 Bump oneAPI headers to v1.3.7.
  O/oneAPI_Level_Zero/common.jl
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Headers/build_tarballs.jl
Labels: oneAPI :one:

#4522 Bump oneAPI loader to v1.7.9.
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Loader/build_tarballs.jl
Labels: oneAPI :one:

#4524 Bump NEO to 22.08.22549.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#4536 Bump LLVMExtra.
  L/LLVMExtra/build_tarballs.jl
Labels: LLVM :dragon:

#4557 [CompilerSupportLibraries] Use new libraries for aarch64-apple-darwin
  C/CompilerSupportLibraries/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#4483 [CUDNN] Added CUDNN for CUDA 10.2 on aarch64-linux-gnu
  C/CUDNN/build_10.2.jl
  C/CUDNN/build_11.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#4574 Changed CUDNN to package v8.2.4
  C/CUDNN/build_10.2.jl
  C/CUDNN/build_11.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:

#4600 [libblastrampoline] Fix complex return style issues on Windows x86_64
  L/libblastrampoline/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#4599 [Rust] Bump RootFS Rust to 1.59.0
  0_RootFS/Rust/build_tarballs.jl
Labels: BinaryBuilder :gear:

#4593 [VegaFusion] Bump to version 0.1.0
  V/VegaFusion/build_tarballs.jl
Labels: rust :crab:

#4623 [AZP] Fix error logging message when list of platforms is empty
  azure-pipelines.yml
Labels: meta :deciduous_tree:

#4622 [gitoxide] Add builder
  G/gitoxide/build_tarballs.jl
Labels: rust :crab:

#4347 Added TensorRT v8.0.1
  T/TensorRT/build_10.2.jl
  T/TensorRT/build_11.0.jl
  T/TensorRT/build_11.1.jl
  T/TensorRT/build_11.2.jl
  T/TensorRT/build_11.3.jl
  T/TensorRT/build_11.jl
  T/TensorRT/build_tarballs.jl
Labels: cuda :joystick:

#4660 Update NCCL to v2.12.7.
  N/NCCL/build_10.2.jl
  N/NCCL/build_11.0.jl
  N/NCCL/build_11.4.jl
  N/NCCL/build_11.6.jl
  N/NCCL/build_tarballs.jl
Labels: cuda :joystick:

#4589 [cuQuantum] Add recipe
  C/cuQuantum/build_tarballs.jl
Labels: cuda :joystick:

#4677 Add a CUDA JLL for actually loading the runtime libraries.
  C/CUDA/CUDA_Runtime/build_10.0.jl
  C/CUDA/CUDA_Runtime/build_10.2.jl
  C/CUDA/CUDA_Runtime/build_11.0.jl
  C/CUDA/CUDA_Runtime/build_11.1.jl
  C/CUDA/CUDA_Runtime/build_11.2.jl
  C/CUDA/CUDA_Runtime/build_11.3.jl
  C/CUDA/CUDA_Runtime/build_11.4.jl
  C/CUDA/CUDA_Runtime/build_11.5.jl
  C/CUDA/CUDA_Runtime/build_11.6.jl
  C/CUDA/CUDA_Runtime/build_tarballs.jl
  platforms/cuda.jl
Labels: cuda :joystick:

#4680 Bump IGC to 1.0.10409.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#4681 Bump NEO to 22.11.22682.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:
