Repository JuliaPackaging/Yggdrasil, pull requests merged in 2022-02, with the labels that each got.

#4362 [RootFS] Back to phrack for Mac
  0_RootFS/PlatformSupport/build_tarballs.jl
Labels: BinaryBuilder :gear:

#4370 [Musl] Upgrade to v1.2.2
  M/Musl/build_tarballs.jl
Labels: BinaryBuilder :gear:

#4364 [RootFS] Update base Alpine Linux image to v3.15 and various utils to more recent versions
  0_RootFS/Rootfs/build_tarballs.jl
  0_RootFS/Rootfs/bundled/libs/libc/download_libcs.sh
  0_RootFS/Rootfs/bundled/utils/flagon
Labels: BinaryBuilder :gear:

#4371 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4374 [RootFS] Drop alpine todo post 3.15 update
  0_RootFS/Rootfs/build_tarballs.jl
Labels: BinaryBuilder :gear:

#3915 [GTK4] Add builder
  G/GTK4/build_tarballs.jl
  G/GTK4/bundled/patches/0001-Include-gdk-private.h-to-fix-error-about-g_source_se.patch
  G/GTK4/bundled/patches/0001-gdkjpeg-include-stdlib.h-necessary-for-free.patch
Labels: GTK :computer:, long shot :bow_and_arrow:

#3962 Upgrade libgit2 to 1.3.0
  L/LibGit2/build_tarballs.jl
  L/LibGit2/bundled/patches/libgit2-continue-zlib.patch
  L/LibGit2/bundled/patches/libgit2-hostkey.patch
Labels: julia :purple_heart: :heart: :green_heart:

#4415 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4421 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4424 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4200 Bump (Lib)CURL to 7.81.0
  L/LibCURL/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#4426 [AZP] Update BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4431 [AZP] Update BinaryBuilder and BinaryBuilderBase
  .ci/Manifest.toml
Labels: meta :deciduous_tree:

#4437 [CI] Add GitHub Actions workflow to automatically update manifest
  .ci/Manifest.toml
  .ci/Project.toml
  .ci/update_manifest.jl
  .github/workflows/update_manifest.yml
Labels: meta :deciduous_tree:

#4349 [CUDA_full] Added CUDA 10.2 for aarch64-linux-gnu
  C/CUDA/CUDA_full@10.2/build_tarballs.jl
Labels: cuda :joystick:

#4475 [CUDA_full] 10.2 - minor fixes for aarch64-linux-gnu
  C/CUDA/CUDA_full@10.2/build_tarballs.jl
Labels: cuda :joystick:

#4482 LLVMExtra: Add build for Julia 1.9
  L/LLVMExtra/build_tarballs.jl
Labels: LLVM :dragon:

#4486 [0_RootFS] Update Go toolchain to v1.17.7
  0_RootFS/Go/build_tarballs.jl
Labels: BinaryBuilder :gear:

#4439 Adapted CUDA_loader and CUDA@10.2 for CUDA_full for aarch64-linux-gnu
  C/CUDA/CUDA@10.2/build_tarballs.jl
  C/CUDA/CUDA_loader/build_10.2.jl
Labels: cuda :joystick:

#4485 [OpenBLAS] Add v0.3.20
  O/OpenBLAS/OpenBLAS32@0.3.20/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.20/bundled/patches/0001-Guard-uses-of-_mm512_reduce_add_p.patch
  O/OpenBLAS/OpenBLAS32@0.3.20/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.20/bundled/patches/openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS32@0.3.20/bundled/patches/openblas-winexit.patch
  O/OpenBLAS/OpenBLAS@0.3.20/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.20/bundled/patches/0001-Guard-uses-of-_mm512_reduce_add_p.patch
  O/OpenBLAS/OpenBLAS@0.3.20/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.20/bundled/patches/openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS@0.3.20/bundled/patches/openblas-winexit.patch
  O/OpenBLAS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:, linear algebra :1234:
