Repository JuliaPackaging/Yggdrasil, pull requests merged in 2022-04, with the labels that each got.

#4707 [Rootfs] Remove duplicate license
  0_RootFS/Rootfs/bundled/licenses/MPL
Labels: BinaryBuilder :gear:

#4748 [0_RootFS] Add LLVMBootstrap v13
  0_RootFS/LLVMBootstrap@13/build_tarballs.jl
  0_RootFS/LLVMBootstrap@13/bundled/patches/0002-llvm8_libcxx_musl.patch
  0_RootFS/LLVMBootstrap@13/bundled/patches/0010-add-musl-triples.patch
  0_RootFS/LLVMBootstrap@13/bundled/patches/0100-llvm-13-musl-bb.patch
  0_RootFS/llvm_common.jl
Labels: BinaryBuilder :gear:

#4780 [Pathfinder] Depend on `cbindgen_jll` instead of using cargo
  P/Pathfinder/build_tarballs.jl
Labels: rust :crab:

#4774 Add kerberos support to LibCURL on linux
  L/LibCURL/LibCURL/build_tarballs.jl
  L/LibCURL/common.jl
Labels: julia :purple_heart: :heart: :green_heart:

#4828 IGC: cherry-pick change to fix miscompilation.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#4829 Bump gmmlib to v22.1.2.
  G/gmmlib/build_tarballs.jl
Labels: oneAPI :one:

#4830 Bump oneAPI headers and loader to v1.7.15.
  O/oneAPI_Level_Zero/common.jl
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Headers/build_tarballs.jl
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Loader/build_tarballs.jl
Labels: oneAPI :one:

#4831 Bump libigc to v1.0.10988.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#4833 Bump NEO to v22.16.22992.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#4845 Bump libigc to v1.0.11061.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#4852 Bump NEO to v22.17.23034.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:
