Repository JuliaPackaging/Yggdrasil, pull requests merged in 2022-06, with the labels that each got.

#4792 [LLVMOpenMP] Update to v14.0.4
  L/LLVMOpenMP/build_tarballs.jl
Labels: LLVM :dragon:

#5050 Bump SPIR-V to LLVM translator, add LLVM 14.
  S/SPIRV_LLVM_Translator_unified/build_tarballs.jl
Labels: oneAPI :one:

#5051 [hyper] Update to v0.14.19
  H/hyper/build_tarballs.jl
  H/hyper/bundled/patches/revert-dont-build-c-lib.patch
Labels: rust :crab:

#5068 Bump libigc to v1.0.11378.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#5078 [AZP] Fix display of PkgServer URL
  azure-pipelines.yml
Labels: meta :deciduous_tree:
