Repository JuliaPackaging/Yggdrasil, pull requests merged in 2023-06, with the labels that each got.

#6861 Bump LLVMExtra
  L/LLVMExtra/build_tarballs.jl
Labels: LLVM :dragon:

#6864 [Lua] Update to v5.4.6
  L/Lua/build_tarballs.jl
  L/Lua/bundled/patches/src_Makefile.patch
  L/Lua/bundled/patches/src_lauxlib.c.patch
Labels: Lua :moon:

#6871 [0_RootFS] Backport to GCC 12.1 patch to fix libgomp on Windows
  0_RootFS/GCCBootstrap@12/bundled/patches/gcc1220-libgomp-win.patch
Labels: Windows 🙄, BinaryBuilder :gear:

#6874 [CompilerSupportLibraries] Get new build of GCC 12 for Windows with libgomp fix
  C/CompilerSupportLibraries/CompilerSupportLibraries@v1.0/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#6881 CUDA: Bump CUDNN to v8.9.2.
  C/CUDNN/build_11.jl
  C/CUDNN/build_12.jl
  C/CUDNN/build_tarballs.jl
Labels: cuda :joystick:
