Repository JuliaPackaging/Yggdrasil, pull requests merged in 2023-04, with the labels that each got.

#6516 [tectonic] Update to 0.12.0, set openssl compat
  T/tectonic/build_tarballs.jl
Labels: rust :crab:

#6523 CUDA: Protect against invalidly-typed preferences.
  C/CUDA/CUDA_Runtime/platform_augmentation.jl
Labels: cuda :joystick:

#6567 CUDA: Bump CUTENSOR JLL.
  C/CUTENSOR/build_tarballs.jl
Labels: cuda :joystick:

#6596 CUDA: Make sure platform augmentation is compatible with older JLLs.
  C/CUDA/CUDA_Runtime/platform_augmentation.jl
Labels: cuda :joystick:

#6603 oneAPI: Bump headers to API spec 1.5.8.
  O/oneAPI_Level_Zero/common.jl
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Headers/build_tarballs.jl
Labels: oneAPI :one:

#6605 oneAPI: Bump loader to v1.9.4.
  O/oneAPI_Level_Zero/oneAPI_Level_Zero_Loader/build_tarballs.jl
Labels: oneAPI :one:

#6604 oneAPI: Bump IGC to v1.0.13230.7.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#6607 oneAPI: Bump NEO to v22.53.25593.11.
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#6606 oneAPI: Bump support library.
  O/oneAPI_Support/build_tarballs.jl
Labels: oneAPI :one:

#6616 [CI] Reduce size of individual depots to 150 GiB
  .buildkite/pipeline.yml.signature
  .buildkite/utils.jl
Labels: meta :deciduous_tree:

#6618 oneAPI: Add debug flavor of libigc_jll.
  L/libigc/build_tarballs.jl
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#6622 oneAPI: Fix julia_compat of JLLs.
  L/libigc/build_tarballs.jl
  N/NEO/build_tarballs.jl
Labels: oneAPI :one:

#6629 oneAPI: Restore IGC OpenCL support.
  L/libigc/build_tarballs.jl
Labels: oneAPI :one:

#6636 CUDA: Update Runtime JLL to 12.1.1.
  C/CUDA/CUDA_Runtime/build_12.1.jl
  C/CUDA/CUDA_Runtime/build_tarballs.jl
Labels: cuda :joystick:

#6660 CUDA: Bump CUDA_Runtime_jll@0.2
  C/CUDA/CUDA_Runtime@0.2/build_tarballs.jl
Labels: cuda :joystick:
