Repository JuliaPackaging/Yggdrasil, pull requests merged in 2024-12, with the labels that each got.

#9915 LLVM: Bump IR downgrader.
  L/LLVMDowngrader/build_tarballs.jl
Labels: LLVM :dragon:

#9923 CUDA/CUDA_Driver: Update to CUDA 12.7
  C/CUDA/CUDA_Driver/build_tarballs.jl
Labels: cuda :joystick:

#10053 LLVM: Bump downgrader
  L/LLVMDowngrader/build_tarballs.jl
Labels: LLVM :dragon:

#8468 0_RootFS: Support riscv64
  0_RootFS/PlatformSupport/build_tarballs.jl
  0_RootFS/gcc_common.jl
  0_RootFS/gcc_sources.jl
  RootFS.md
Labels: BinaryBuilder :gear:

#10085 [Zlib] Rebuild for RISC-V
  Z/Zlib/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10086 [nghttp2] Rebuild for RISC-V
  N/nghttp2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10087 [LibUV] Rebuild for RISC-V
  L/LibUV/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10089 [OpenLibm] Rebuild for RISC-V
  O/OpenLibm/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10088 [GMP] Rebuild for RISC-V
  G/GMP/GMP@6.2.1/build_tarballs.jl
  G/GMP/GMP@6.3.0/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10090 [PCRE2] Rebuild for RISC-V
  P/PCRE2/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10093 [dSFMT] Rebuild for RISC-V
  D/dSFMT/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10092 [p7zip] Rebuild for RISC-V
  P/p7zip/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10094 OpenSSL: Build for riscv64
  O/OpenSSL/OpenSSL@3.0/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10079 Rustfs: Update to 1.83.0
  0_RootFS/Rust/build_tarballs.jl
Labels: BinaryBuilder :gear:, rust :crab:

#10083 [RootFS] Do not link to libquadmath in RISC-V Fortran tests
  0_RootFS/Rootfs/bundled/testsuite/fortran/hello_world/Makefile
Labels: BinaryBuilder :gear:

#10142 [Zlib@1.2.12] Rebuild for riscv64
  Z/Zlib/Zlib@1.2.12/build_tarballs.jl
  Z/Zlib/build_tarballs.jl
  Z/Zlib/common.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10141 [CI] Downgrade `ghr` to v0.14 and rebuild Enzyme
  .ci/Manifest.toml
  .ci/Project.toml
  E/Enzyme/build_tarballs.jl
Labels: meta :deciduous_tree:

#10158 [CI] Update Manifest
  .ci/Manifest.toml
Labels: ci
