Repository JuliaPackaging/Yggdrasil, pull requests merged in 2024-01, with the labels that each got.

#7895 CUDA: Bump SDK to v12.3.2.
  C/CUDA/CUDA_SDK@12.3/build_tarballs.jl
  C/CUDA/CUDA_SDK_static@12.3/build_tarballs.jl
  platforms/cuda.jl
Labels: cuda :joystick:

#7894 CUDA: Bump driver to 545.23.08.
  C/CUDA/CUDA_Driver/build_tarballs.jl
Labels: cuda :joystick:

#7897 CUDA: Bump runtime for 12.3.2.
  C/CUDA/CUDA_Runtime/build_tarballs.jl
Labels: cuda :joystick:

#7911 [OpenBLAS] Update to v0.3.26
  O/OpenBLAS/OpenBLAS32@0.3.26/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/10-neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/30-openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/50-openblas-winexit.patch
  O/OpenBLAS/OpenBLAS@0.3.26/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/10-neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/30-openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/50-openblas-winexit.patch
  O/OpenBLAS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:, linear algebra :1234:

#7920 Add recipe for object_store_ffi
  O/object_store_ffi/build_tarballs.jl
Labels: rust :crab:

#7859 [LLVM_full] Bump to v17
  L/LLVM/LLVM_full@17/build_tarballs.jl
  L/LLVM/LLVM_full@17/bundled/libcxx_patches/7005_libcxx_musl.patch
  L/LLVM/LLVM_full@17/bundled/patches/0001-Disable-tblgen-lsp-server.patch
  L/LLVM/LLVM_full@17/bundled/patches/0050-unique_function_clang-sa.patch
  L/LLVM/LLVM_full@17/bundled/patches/0100-llvm-12-musl-bb.patch
  L/LLVM/LLVM_full@17/bundled/patches/0200-templates.patch
  L/LLVM/LLVM_full@17/bundled/patches/0300-mingw-mlir-visibility-hidden.patch
  L/LLVM/LLVM_full@17/bundled/patches/0704-no-codesign.patch
  L/LLVM/LLVM_full_assert@17/build_tarballs.jl
  L/LLVM/LLVM_full_assert@17/bundled
  L/LLVM/common.jl
Labels: LLVM :dragon:, julia :purple_heart: :heart: :green_heart:

#7932 [SuiteSparse_GPU] Update to 7.5.0 and fix CUDA logic
  S/SuiteSparse/SuiteSparse_GPU@7/build_tarballs.jl
  S/SuiteSparse/common.jl
Labels: cuda :joystick:, linear algebra :1234:

#7969 update devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: meta :deciduous_tree:

#7202 [OpenBLAS] Build the BFloat16 kernels in OpenBLAS
  O/OpenBLAS/OpenBLAS32@0.3.23/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.23/bundled/patches/60-gemv-multithreading.patch
  O/OpenBLAS/OpenBLAS32@0.3.23/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/10-neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/60-gemv-multithreading.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/80-avx512bf-kernels.patch
  O/OpenBLAS/OpenBLAS32@0.3.26/bundled/patches/90-darwin-sve.patch
  O/OpenBLAS/OpenBLAS@0.3.23/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.23/bundled/patches/60-gemv-multithreading.patch
  O/OpenBLAS/OpenBLAS@0.3.23/bundled/patches/neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.26/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/10-neoverse-generic-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/60-gemv-multithreading.patch
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/80-avx512bf-kernels.patch
  O/OpenBLAS/OpenBLAS@0.3.26/bundled/patches/90-darwin-sve.patch
  O/OpenBLAS/common.jl
Labels: linear algebra :1234:
