Repository JuliaPackaging/Yggdrasil, pull requests merged in 2025-01, with the labels that each got.

#10216 [OpenLibm] Update to 0.8.5
  O/OpenLibm/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10253 [CompilerSupportLibraries] New version with GCC 14
  C/CompilerSupportLibraries/CompilerSupportLibraries@v1.3/build_tarballs.jl
Labels: julia :purple_heart: :heart: :green_heart:

#10099 OpenBLAS: update to v0.3.29
  O/OpenBLAS/OpenBLAS32@0.3.29/build_tarballs.jl
  O/OpenBLAS/OpenBLAS32@0.3.29/bundled/patches/10-disable-running-tests.patch
  O/OpenBLAS/OpenBLAS32@0.3.29/bundled/patches/30-openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS32@0.3.29/bundled/patches/50-openblas-winexit.patch
  O/OpenBLAS/OpenBLAS32@0.3.29/bundled/patches/70-Build-with-proper-aarch64-flags-on-Neoverse-Darwin.patch
  O/OpenBLAS/OpenBLAS@0.3.29/build_tarballs.jl
  O/OpenBLAS/OpenBLAS@0.3.29/bundled/patches/10-disable-running-tests.patch
  O/OpenBLAS/OpenBLAS@0.3.29/bundled/patches/30-openblas-ofast-power.patch
  O/OpenBLAS/OpenBLAS@0.3.29/bundled/patches/50-openblas-winexit.patch
  O/OpenBLAS/OpenBLAS@0.3.29/bundled/patches/70-Build-with-proper-aarch64-flags-on-Neoverse-Darwin.patch
  O/OpenBLAS/common.jl
Labels: julia :purple_heart: :heart: :green_heart:, linear algebra :1234:

#10351 CUDA: Update driver to v12.8.
  C/CUDA/CUDA_Driver/build_tarballs.jl
Labels: cuda :joystick:

#10353 CUDA: Update runtime and SDK to v12.8.
  C/CUDA/CUDA_Runtime/build_12.8.jl
  C/CUDA/CUDA_Runtime/build_tarballs.jl
  C/CUDA/CUDA_SDK@12.8/build_tarballs.jl
  C/CUDA/CUDA_SDK_static@12.8/build_tarballs.jl
  platforms/cuda.jl
Labels: cuda :joystick:
