Repository JuliaPackaging/Yggdrasil, pull requests merged in 2025-08, with the labels that each got.

#11784 CUDA: Rebuild 12.9 static SDK using xz.
  C/CUDA/CUDA_SDK_static@12.9/build_tarballs.jl
  C/CUDA/common.jl
Labels: cuda :joystick:

#11720 oneAPI: Bump NEO to v25.27.34303.5
  N/NEO/build_tarballs.jl
  N/NEO/bundled/ocloc_wrapper.sh
  N/NEO/bundled/patches/ocloc.patch
Labels: oneAPI :one:

#11792 CUDA: Bump NVTX to v3.2.2
  N/NVTX/build_tarballs.jl
Labels: cuda :joystick:

#11833 [CI] Downgrade HistoricalStdlibVersions to v2.0.2
  .ci/Manifest.toml
  .ci/Project.toml
Labels: meta :deciduous_tree:

#11903 Update compiler shard versions in docs
  RootFS.md
Labels: meta :deciduous_tree:

#11936 [Lua] Update to 5.4.8
  L/Lua/build_tarballs.jl
Labels: Lua :moon:

#11955 Don't request reviews when doing component notifications
  .github/workflows/component_owners.yml
Labels: meta :deciduous_tree:

#11961 Add kalmarek to component_owners.yml
  .github/component_owners.yml
Labels: meta :deciduous_tree:
